### ISSUE TITLE
Ticket all garbled in osTicket 1.10.4  - Solution

### ISSUE THREAD

**Issue by modF** [LiveHelperChat/osTicket#8]
If you change line 139 in bootstrap.php to

`'message' => 'data:text/html,' . str_replace(array(`

You can then add some break tags to the ticket template and the ticket will be readable. 

Sorry if this is in the wrong spot, I do not have push access.   Also, the osTicket API docs say this should be type and not data, but that does not work, and they used data in their actual example.

**Comment by Pietro-Aretino** [comment]
Don't know if this is the place to put this error, but when I go to 'create a ticket' I get an web-browser pop-up that notifies me of the following error:
```
Unable to create ticket: <!DOCTYPE HTML PUBLIC"-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.</p>
</body></html>
```
EDIT: This error ^ is due to Kerberos configuration on my part. This has been fixed but adding an .htaccess file to LHC directory to allow kerberos authentication pass through.

However now I am confronted with this error:

```
Unable to create ticket: Unable to create new ticket: validation errors:
user: Incomplete client information

```
The above error ^ is due to two things:
A) Make sure your osTicket form has the required fields identical to what Live Helper is using e.g. phone, email, name etc.
B) The REAL issue is that if the User is not already in your User directory within osTicket, this extension is incapable of telling osTicket to CREATE the user. If this got fixed, this would work great.

**Comment by remdex** [comment]
1. Updated extension with few more options in integration window. You will be able to
1.1 "Use E-mail as visitor name. Will be used to e-mail send name attribute"
1.2 "If chat does not have an e-mail use this"
1.3 "Do not use chat nick and use this text value as client name"

2. Above issue with not supported html tags also fixed. Just new line to br added.
3. As for creating user. I'm not sure how can i help about that. As i tested now it creates user based on provided e-mail. So if chat has e-mail it sends info with chat e-mail and user with same e-mail from previous issues is assigned to same issue... Perhaps i'm missing something not sure.
